# Common Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Common Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
